package com.minesafe.ar.training

enum class TrainingState {
    START,
    SCAN_FLOOR,
    PLACE_DOORWAY,
    ENTER_MINE,
    FIRE_DETECTED,
    GO_TO_EXTINGUISHER,
    EXTINGUISHER_REACHED,
    OPEN_SAFETY_MECHANISM,
    AIM_AT_FIRE,
    DISCHARGE_EXTINGUISHER,
    FIRE_EXTINGUISHED,
    TRAINING_COMPLETE
}
